//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public int NetWorkId { get; set; }
        public string SAPActivity { get; set; }
        public string SAPNetwork { get; set; }
        public Nullable<int> WBSAreaId { get; set; }
        public string SAPSite { get; set; }
        public string SAPProject { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual NetWork NetWork { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
