//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignEngineerDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DesignEngineerDocument()
        {
            this.DocumentReviewDetails = new HashSet<DocumentReviewDetail>();
            this.DEDocumentFiles = new HashSet<DEDocumentFile>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Comments { get; set; }
        public int Version { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> SubActivityId { get; set; }
        public string SAPSite { get; set; }
        public string SAPProject { get; set; }
        public int WBSAreaId { get; set; }
        public string SAPNetwork { get; set; }
        public string SAPActivity { get; set; }
        public string SAPSubActivity { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public bool ReleaseToContsruction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentReviewDetail> DocumentReviewDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEDocumentFile> DEDocumentFiles { get; set; }
    }
}
