//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    
    public partial class DesignEngineerDocuments
    {
        public string FileName { get; set; }
        public string Comments { get; set; }
        public int Version { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UserId { get; set; }
        public int Id { get; set; }
        public int DocumentDetailsId { get; set; }
    }
}
