//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentReviewDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentReviewDetail()
        {
            this.DocumentReviewFiles = new HashSet<DocumentReviewFile>();
        }
    
        public int Id { get; set; }
        public int DEDocumentVersion { get; set; }
        public int DEDocumentId { get; set; }
        public string ReviewComments { get; set; }
        public string ReviewDescription { get; set; }
        public string FilePath { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual DesignEngineerDocument DesignEngineerDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentReviewFile> DocumentReviewFiles { get; set; }
    }
}
