//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscalationMatrix
    {
        public int EscalationMatrixId { get; set; }
        public Nullable<int> ActivityTakingLongerThanPlanned { get; set; }
        public Nullable<int> IssueNotResolved { get; set; }
        public Nullable<int> IssueNotClosed { get; set; }
        public Nullable<int> QualityIssueNotResolved { get; set; }
        public Nullable<int> QualityRejectionNotClosed { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
