//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerTimesheetSurveyDetail
    {
        public int TimesheetSurveyDetailId { get; set; }
        public int TimesheetId { get; set; }
        public int VillageId { get; set; }
        public string SurveyNo { get; set; }
        public int ActualNoOfDivision { get; set; }
        public decimal ActualArea { get; set; }
        public short Status { get; set; }
        public short ManagerType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Timesheet Timesheet { get; set; }
    }
}
