//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    
    public partial class ManPowerMasterDetails
    {
        public string Site { get; set; }
        public string Project { get; set; }
        public string ProjectDescription { get; set; }
        public string WBSArea { get; set; }
        public string Network { get; set; }
        public string NetworkDescription { get; set; }
        public int CanEdit { get; set; }
        public int AreaId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
