//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfflineTimesheet
    {
        public int Id { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> SubActivityId { get; set; }
        public string SAPSite { get; set; }
        public string SAPProject { get; set; }
        public Nullable<int> WBSAreaId { get; set; }
        public string SAPNetwork { get; set; }
        public string SAPActivity { get; set; }
        public string SAPSubActivity { get; set; }
        public System.DateTime ActualDate { get; set; }
        public Nullable<decimal> ActualQuantity { get; set; }
        public string Comments { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Reason { get; set; }
        public bool IsValid { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
