//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    
    public partial class SubmittedTimesheetDetails
    {
        public System.DateTime ActualDate { get; set; }
        public Nullable<decimal> ActualQuantity { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public int TimeSheetId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public int SubActivityId { get; set; }
        public int UserId { get; set; }
        public int AllowEdit { get; set; }
    }
}
