//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyMasterStaging
    {
        public int SurveyId { get; set; }
        public string SurveyNo { get; set; }
        public string Site { get; set; }
        public Nullable<int> VillageId { get; set; }
        public string VillageName { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<int> NoOfDivision { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> IsValidated { get; set; }
        public Nullable<bool> IsMerged { get; set; }
        public string ProjectId { get; set; }
    }
}
