//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    
    public partial class TimesheetBlockDetailsView
    {
        public Nullable<int> ActualQuantity { get; set; }
        public Nullable<int> BlockNo { get; set; }
        public int Quantity { get; set; }
        public int TimesheetBlockDetailId { get; set; }
        public int TimesheetId { get; set; }
        public short ManagerType { get; set; }
    }
}
