//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timesheet()
        {
            this.ManagerTimesheetActivities = new HashSet<ManagerTimesheetActivity>();
            this.ManagerTimesheetBlockDetails = new HashSet<ManagerTimesheetBlockDetail>();
            this.ManagerTimesheetSurveyDetails = new HashSet<ManagerTimesheetSurveyDetail>();
            this.TimesheetActivities = new HashSet<TimesheetActivity>();
            this.TimesheetApprovals = new HashSet<TimesheetApproval>();
            this.TimesheetAttachments = new HashSet<TimesheetAttachment>();
            this.TimesheetBlockDetails = new HashSet<TimesheetBlockDetail>();
            this.TimesheetSurveyDetails = new HashSet<TimesheetSurveyDetail>();
        }
    
        public int TimeSheetId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> SubActivityId { get; set; }
        public string SAPSite { get; set; }
        public string SAPProject { get; set; }
        public Nullable<int> WBSAreaId { get; set; }
        public string SAPNetwork { get; set; }
        public string SAPActivity { get; set; }
        public string SAPSubActivity { get; set; }
        public System.DateTime ActualDate { get; set; }
        public Nullable<decimal> ActualQuantity { get; set; }
        public Nullable<decimal> QAApprovedQuantity { get; set; }
        public Nullable<decimal> ApprovedQuantity { get; set; }
        public string Comments { get; set; }
        public Nullable<int> WorkflowStatusId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> SAPCallSuccess { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerTimesheetActivity> ManagerTimesheetActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerTimesheetBlockDetail> ManagerTimesheetBlockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerTimesheetSurveyDetail> ManagerTimesheetSurveyDetails { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetActivity> TimesheetActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetApproval> TimesheetApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetAttachment> TimesheetAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetBlockDetail> TimesheetBlockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetSurveyDetail> TimesheetSurveyDetails { get; set; }
    }
}
