//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    
    public partial class TimesheetActivityDetails
    {
        public string SAPNetwork { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public int SubActivityId { get; set; }
        public string SAPActivity { get; set; }
        public string SapSubActivity { get; set; }
        public string ActivityDescription { get; set; }
        public string SAPSubActivityDescription { get; set; }
        public decimal ActivityQty { get; set; }
        public string ActivityPlanQtyUoM { get; set; }
        public Nullable<System.DateTime> ActivityPlanStartDate { get; set; }
        public Nullable<System.DateTime> ActivityActualFinishDate { get; set; }
        public Nullable<System.DateTime> ActivityActualStartDate { get; set; }
        public Nullable<System.DateTime> ActivityPlanFinishDate { get; set; }
        public Nullable<int> EstimatedDuration { get; set; }
        public Nullable<int> ActualDuration { get; set; }
        public string ActivityCompletionStatus { get; set; }
        public int UserId { get; set; }
        public string SAPProjectId { get; set; }
        public string WBSArea { get; set; }
        public int TimeSheetId { get; set; }
        public int StatusId { get; set; }
        public string MobileFunction { get; set; }
        public string BlockTable { get; set; }
        public int WBSAreaId { get; set; }
        public string SAPSite { get; set; }
        public Nullable<decimal> ActualQty { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public int CreatedBy { get; set; }
        public int WorkflowStatusId { get; set; }
    }
}
