//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarPMS.Models
{
    using System;
    
    public partial class usp_ToDoListRejected_Result1
    {
        public int TimeSheetId { get; set; }
        public string SAPSite { get; set; }
        public string ProjectDescription { get; set; }
        public string NetworkDescription { get; set; }
        public string WBSArea { get; set; }
        public string ActivityDescription { get; set; }
        public string SAPSubActivityDescription { get; set; }
        public Nullable<decimal> ActivityQty { get; set; }
        public string ActivityPlanQtyUoM { get; set; }
        public System.DateTime ActivityPlanStartDate { get; set; }
        public System.DateTime ActivityPlanFinishDate { get; set; }
        public System.DateTime ActualDate { get; set; }
        public Nullable<decimal> ActualQuantity { get; set; }
        public string WorkflowStatus { get; set; }
        public string UserName { get; set; }
        public int ActivityId { get; set; }
        public int SubActivityId { get; set; }
    }
}
