//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuzlonBPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentWorkflow
    {
        public int PaymentWorkFlowId { get; set; }
        public int SubVerticalId { get; set; }
        public int VerticalId { get; set; }
        public int PriAggUserId { get; set; }
        public int PriContUserId { get; set; }
        public int PriExpAppUserId { get; set; }
        public int PriAuditorUserId { get; set; }
        public int PriFASSCDTUserId { get; set; }
        public int PriFASSCCBUserId { get; set; }
        public Nullable<int> SecAggUserId { get; set; }
        public Nullable<int> SecContUserId { get; set; }
        public Nullable<int> SecExpAppUserId { get; set; }
        public Nullable<int> SecAuditorUserId { get; set; }
        public Nullable<int> SecFASSCDTUserId { get; set; }
        public Nullable<int> SecFASSCCBUserId { get; set; }
        public Nullable<System.DateTime> SecAggFromDt { get; set; }
        public Nullable<System.DateTime> SecAggToDt { get; set; }
        public Nullable<System.DateTime> SecContFromDt { get; set; }
        public Nullable<System.DateTime> SecContToDt { get; set; }
        public Nullable<System.DateTime> SecExpAppFromDt { get; set; }
        public Nullable<System.DateTime> SecExpAppToDt { get; set; }
        public Nullable<System.DateTime> SecAuditorFromDt { get; set; }
        public Nullable<System.DateTime> SecAuditorToDt { get; set; }
        public Nullable<System.DateTime> SecFASSCDTFromDt { get; set; }
        public Nullable<System.DateTime> SecFASSCDTToDt { get; set; }
        public Nullable<System.DateTime> SecFASSCCBFromDt { get; set; }
        public Nullable<System.DateTime> SecFASSCCBToDt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual SubVerticalMaster SubVerticalMaster { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual VerticalMaster VerticalMaster { get; set; }
    }
}
