//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuzlonBPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetailAdvanceTxn
    {
        public int PaymentDetailAdvanceTxnId { get; set; }
        public int SAPAdvancePaymentId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public int PaymentWorkflowStatusId { get; set; }
        public Nullable<decimal> AppovedAmount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SubVerticalId { get; set; }
    
        public virtual PaymentWorkflowStatu PaymentWorkflowStatu { get; set; }
        public virtual ProfileMaster ProfileMaster { get; set; }
        public virtual SAPAdvancePayment SAPAdvancePayment { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        public virtual User User { get; set; }
    }
}
