//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuzlonBPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetailAdvance
    {
        public int PaymentDetailAdvanceId { get; set; }
        public int SAPAdvancePaymentId { get; set; }
        public Nullable<int> SubVerticalId { get; set; }
        public Nullable<int> VerticalId { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PaymentWorkFlowStatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ApprovedLineItemID { get; set; }
        public string ApprovedLineGroupID { get; set; }
        public Nullable<int> TransactionStatusId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<bool> SaveMode { get; set; }
        public string DocumentClearingNo { get; set; }
    
        public virtual PaymentWorkflowStatu PaymentWorkflowStatu { get; set; }
        public virtual SAPAdvancePayment SAPAdvancePayment { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        public virtual SubVerticalMaster SubVerticalMaster { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual VerticalMaster VerticalMaster { get; set; }
        public virtual ProfileMaster ProfileMaster { get; set; }
    }
}
