//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuzlonBPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreasuryWorkflow
    {
        public int TreasuryWorkFlowId { get; set; }
        public int SubVerticalId { get; set; }
        public int VerticalId { get; set; }
        public int PriVerContUserId { get; set; }
        public int PriTreasuryUserId { get; set; }
        public int PriCBUserId { get; set; }
        public Nullable<int> SecVerContUserId { get; set; }
        public Nullable<int> SecTreasuryUserId { get; set; }
        public Nullable<int> SecCBUserId { get; set; }
        public Nullable<System.DateTime> SecVerContFromDt { get; set; }
        public Nullable<System.DateTime> SecVerContToDt { get; set; }
        public Nullable<System.DateTime> SecTreasuryFromDt { get; set; }
        public Nullable<System.DateTime> SecTreasuryToDt { get; set; }
        public Nullable<System.DateTime> SecCBFromDt { get; set; }
        public Nullable<System.DateTime> SecCBToDt { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual SubVerticalMaster SubVerticalMaster { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual VerticalMaster VerticalMaster { get; set; }
    }
}
