//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuzlonBPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreasuryNatureRequestDetail
    {
        public int TreasuryRequestId { get; set; }
        public int TreasuryId { get; set; }
        public int NatureOfReqestId { get; set; }
        public string NatureOfReqest { get; set; }
        public Nullable<decimal> RequestedAmount { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
