//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuzlonBPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaster
    {
        public int VendorId { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string VendorAccountGroup { get; set; }
        public string PanNo { get; set; }
        public string CentralPostingBlock { get; set; }
        public string CentImpPurchaseBlock { get; set; }
        public string FunctionBlock { get; set; }
        public string PaymentBlock { get; set; }
        public string CentralDeletion { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string CountryKey { get; set; }
        public string Region { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
