//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuzlonBPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorBankMaster
    {
        public int VendorBankId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string AccountNumber { get; set; }
        public string SuzlonEmailID1 { get; set; }
        public string SuzlonEmailID2 { get; set; }
        public string VendorEmailID1 { get; set; }
        public string VendorEmailID2 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.TimeSpan> CreatedTime { get; set; }
        public string UserName { get; set; }
        public string IFSCCode { get; set; }
        public string IFSCCodeRTGS { get; set; }
        public string AccountType { get; set; }
        public string VendorBankName { get; set; }
        public string VendorBranchName { get; set; }
        public string Location { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
