//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuzlonBPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowAudit
    {
        public int AuditId { get; set; }
        public string FieldName { get; set; }
        public int SubVerticalId { get; set; }
        public int ProfileId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> WorkFlowTypeId { get; set; }
        public Nullable<int> WorkFlowId { get; set; }
    
        public virtual ProfileMaster ProfileMaster { get; set; }
        public virtual SubVerticalMaster SubVerticalMaster { get; set; }
        public virtual User User { get; set; }
        public virtual WorkflowConfiguration WorkflowConfiguration { get; set; }
    }
}
